import os

ENLIGHTEN_SYSTEM_ID = os.environ.get(
    'ENLIGHTEN_SYSTEM_ID', 'ENLIGHTEN_SYSTEM_ID not set.')
ENLIGHTEN_API_KEY = os.environ.get(
    'ENLIGHTEN_API_KEY', 'ENLIGHTEN_API_KEY not set.')
ENLIGHTEN_USER_ID = os.environ.get(
    'ENLIGHTEN_USER_ID', 'ENLIGHTEN_USER_ID not set.')
ENLIGHTEN_DATA_MIN_DATE = os.environ.get(
    'ENLIGHTEN_DATA_MIN_DATE', 'ENLIGHTEN_DATA_MIN_DATE not set.')
ENLIGHTEN_STORAGE_PATH_PREFIX = os.environ.get(
    'ENLIGHTEN_STORAGE_PATH_PREFIX', 'ENLIGHTEN_STORAGE_PATH_PREFIX not set.')
